image: gitpod/workspace-mongodb
ports:
  - port: 5000     # default flask port
  - port: 27017    # defsuly mongodb port
tasks:
  - command: mongod  # TODO: figure out how to run commands sequentially?
  - command: pip3 install -r requirements.txt && python3 etl.py && python3 server.py
vscode:
  extensions:
    - ms-python.python@2019.9.34911:NHtRMp5fFB2KUUw72DlGug==